INSERT INTO MENTORMEROLES ( ID, NAME) VALUES ('1', 'USER')
INSERT INTO MENTORMEUSERS  (ID, USERNAME, PASSWORD) VALUES ('1', 'admin', '$2a$10$2lAj3KIS/ddjXXwx80TDnOrEjx1SY73uybK99zj3Q7cZAI3LwguPm')
INSERT INTO MENTORMEUSERS_MENTORMEROLES   ( MENTORMEUSERS_ID, ROLES_ID) VALUES ('1', '1')

