INSERT INTO MENTORMEROLES ( ID, NAME) VALUES ('1', 'USER')
INSERT INTO MENTORMEUSERS  (ID, USERNAME, PASSWORD) VALUES ('1', 'admin', '$2a$10$2lAj3KIS/ddjXXwx80TDnOrEjx1SY73uybK99zj3Q7cZAI3LwguPm')
INSERT INTO MENTORMEUSERS_MENTORMEROLES   ( MENTORMEUSERS_ID, ROLES_ID) VALUES ('1', '1')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('1',  'Data Science & Analytics', 'Data Science & Analytics')
INSERT INTO Course  ( cId, imgurl ,name, description, title) VALUES ('1', 'images/t1.jpg', 'Data Analysis', 'Learning Data Analytics using Microsoft PowerBI','Data Analytics')
INSERT INTO Course  ( cId, imgurl ,name, description, title) VALUES ('2',  'images/t1.jpg', 'Data Analysis', 'Learning Data Analytics using Microsoft PowerBI','Data Analytics')
INSERT INTO Course  ( cId, name, description, title) VALUES ('3',  'Data Analysis', 'Learning Data Analytics using Microsoft PowerBI','Data Analytics')
INSERT INTO Course  ( cId, name, description, title) VALUES ('4',  'Data Analysis', 'Learning Data Analytics using Microsoft PowerBI','Data Analytics')
INSERT INTO Course  ( cId, name, description, title) VALUES ('5',  'Data Analysis', 'Learning Data Analytics using Microsoft PowerBI','Data Analytics')
INSERT INTO Course  ( cId, imgurl , name, description, title, curl) VALUES ('6', 'images/p1.jpg',  'Data Analysis', 'Introduction to Microsoft PowerBI','Learning Data Analytics using Microsoft PowerBI', '1mspowerbi')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('2',  'Microsoft Dynamics', 'Microsoft Dynamics')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('3',  'Web development', 'Web development')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('4',  'Software development', 'Software development')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('5',  'Robotics & Automation', 'Robotics & Automation')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('6',  'Robotics & Automation', 'Robotics & Automation')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('7',  'Design', 'Design')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('8',  'UI/UX Prototyping', 'UI/UX Prototyping')
INSERT INTO DEPARTMENT  ( dId, name, description) VALUES ('9',  'Marketing', 'Marketing')
